"""initial

Revision ID: 3318d31babab
Revises: 
Create Date: 2026-07-01 22:27:59.159628
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '3318d31babab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dragons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('egg_type', sa.String(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('steps_count', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('silhouette_path', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('current_dragon_id', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('state_data', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('collection_grid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_x', sa.Integer(), nullable=False),
    sa.Column('cell_y', sa.Integer(), nullable=False),
    sa.Column('dragon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dragon_id'], ['dragons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_x', 'cell_y'),
    sa.UniqueConstraint('dragon_id')
    )
    op.create_table('dragon_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dragon_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('magic_action', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dragon_id'], ['dragons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('dragon_id', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dragon_id'], ['dragons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_dragons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dragon_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dragon_id'], ['dragons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dragon_id')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dragon_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('photo_before_id', sa.Text(), nullable=True),
    sa.Column('photo_after_id', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dragon_id'], ['dragons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dragon_id', 'step_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_table('user_dragons')
    op.drop_table('pins')
    op.drop_table('dragon_steps')
    op.drop_table('collection_grid')
    op.drop_table('users')
    op.drop_table('dragons')
    # ### end Alembic commands ###
