"""pin_per_dragon

Revision ID: a67adbf490cd
Revises: b59cac4a0ff9
Create Date: 2026-07-02 07:19:24.396574
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'a67adbf490cd'
down_revision: Union[str, None] = 'b59cac4a0ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pins')
    with op.batch_alter_table('dragons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=4), nullable=True))
        batch_op.create_unique_constraint('uq_dragons_pin_code', ['pin_code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragons', schema=None) as batch_op:
        batch_op.drop_constraint('uq_dragons_pin_code', type_='unique')
        batch_op.drop_column('pin_code')

    op.create_table('pins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('dragon_id', sa.INTEGER(), nullable=True),
    sa.Column('rarity', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(), nullable=True),
    sa.Column('used_by', sa.INTEGER(), nullable=True),
    sa.Column('used_at', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['dragon_id'], ['dragons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
