"""add keyword to dragon_steps

Revision ID: b59cac4a0ff9
Revises: 3318d31babab
Create Date: 2026-07-01 22:57:51.752792
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'b59cac4a0ff9'
down_revision: Union[str, None] = '3318d31babab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragon_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dragon_steps', schema=None) as batch_op:
        batch_op.drop_column('keyword')

    # ### end Alembic commands ###
