"""add service_heartbeats

Revision ID: bf1b946df94e
Revises: f922e550f433
Create Date: 2026-07-04 14:51:15.301069
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'bf1b946df94e'
down_revision: Union[str, None] = 'f922e550f433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('last_seen', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_heartbeats')
    # ### end Alembic commands ###
