"""add error_logs

Revision ID: f922e550f433
Revises: f1a2b3c4d5e6
Create Date: 2026-07-04 14:45:15.757391
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'f922e550f433'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('traceback_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dragon_steps', schema=None) as batch_op:
        batch_op.alter_column('timeout_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('timeout_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user_dragons', schema=None) as batch_op:
        batch_op.alter_column('timeout_notified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_dragons', schema=None) as batch_op:
        batch_op.alter_column('timeout_notified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('dragon_steps', schema=None) as batch_op:
        batch_op.alter_column('timeout_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('timeout_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    op.drop_table('error_logs')
    # ### end Alembic commands ###
